In [53]:

import numpy as np
import pandas as pd
import time


In [ ]:
#Task 1 --> Creating Arrays
#1D Array
arr = np.arange(1,11)
print(arr)

#2D Array
arr2 = np.arange(1,10).reshape(3,3)
print(arr2)

#3D Array
arr3 = np.random.rand(3,5,3)
print(arr3)

#-----------------------------------------------------------------

print(arr.shape,arr.size,arr.dtype)
print(arr2.shape,arr2.size,arr2.dtype)
print(arr3.shape,arr3.size,arr3.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[0.2339243  0.32428959 0.55008158]
  [0.72872167 0.1037564  0.15530583]
  [0.97364679 0.76091373 0.08923415]
  [0.51440898 0.34993037 0.07613192]
  [0.1315418  0.66348985 0.13573623]]

 [[0.64716406 0.06394581 0.03522776]
  [0.25409872 0.49039047 0.93209621]
  [0.62677739 0.9983219  0.58410801]
  [0.17163192 0.50012821 0.4426967 ]
  [0.59734038 0.47029672 0.61214   ]]

 [[0.19159065 0.48423208 0.7671066 ]
  [0.55065845 0.1024046  0.53236292]
  [0.13263831 0.84420891 0.87173376]
  [0.68025192 0.95336243 0.21974252]
  [0.19571441 0.58073382 0.95737387]]]
(10,) 10 int32
(3, 3) 9 int32
(3, 5, 3) 45 float64


In [14]:
#Task 2 --> Array Indexing and Slicing
data = np.array([10,20,30,40,50,60,70,80,90])
print(data)

#-----------------------------------------------------------

print("First 3 elements :",data[0:3])
print("Every alternate element :",data[0::2])
print("Reverse array :",data[::-1])






[10 20 30 40 50 60 70 80 90]
First 3 elements : [10 20 30]
Every alternate element : [10 30 50 70 90]
Reverse array : [90 80 70 60 50 40 30 20 10]


In [29]:
#Task 3 --> Mathematical Operations

A=np.random.randint(1,20,5)
print(A)

B = np.random.randint(1,20,5)
print(B)

#--------------------------------------------------------------

print("ADD :",A+B)
print("SUB :",A-B)
print("MUL :",A*B)
print("DIV :",A/B)

print(np.dot(A,B))

print(np.mean(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

print("MAX =",np.max(B),"INDEX =",np.argmax(B))
print("MIN =",np.min(B),"INDEX =",np.argmax(B))

[ 5 19  3  8  4]
[ 4 15  2  9  6]
ADD : [ 9 34  5 17 10]
SUB : [ 1  4  1 -1 -2]
MUL : [ 20 285   6  72  24]
DIV : [1.25       1.26666667 1.5        0.88888889 0.66666667]
407
7.8
5.0
5.844655678480982
34.15999999999999
MAX = 15 INDEX = 1
MIN = 2 INDEX = 1


In [36]:
#Task 4 --> Reshaping and Transposing
arr= np.arange(1,13)
print(arr)

#--------------------------------------------------------

arr2 = arr.reshape(4,3)
print(arr2)

arr3 = arr.reshape(2,2,3)
print(arr3)

transpose = arr2.T
print(transpose,transpose.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] (3, 4)


In [43]:
#Task 5 --> Boolean Masking and Filtering
arr=np.random.randint(10,50,15)
print(arr)

#-----------------------------------------------------------

greater_than_25 = arr[arr > 25]
print("Elements > 25:", greater_than_25)

arr[arr < 30] = 0
print("After replacing <30 with 0:", arr)

div_by_5 = np.sum(arr % 5 == 0)
print("Count of elements divisible by 5:", div_by_5)

[18 28 16 33 24 26 45 17 27 45 35 44 24 38 28]
Elements > 25: [28 33 26 45 27 45 35 44 38 28]
After replacing <30 with 0: [ 0  0  0 33  0  0 45  0  0 45 35 44  0 38  0]
Count of elements divisible by 5: 12


In [ ]:
#Task 6 --> Working with Built-in Functions
arr=np.linspace(0,1,10)
print(arr)

arrI=np.eye(4,4)
print(arrI)

array = np.random.randint(1,100,20)
np.sort(array)
print(array[4])

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[68 76 15 13 29 56 27 99  9 96 11 61 32  2 97 20 76 84 69  6]
29


In [56]:
#Task 7 --> Generic
array1 = np.random.rand(100,100) 
array2 = np.random.rand(100,100) 

start_time=time.time()
result = np.matmul(array1,array2)
print(result)


det = np.linalg.det(result)
print("Determinant:", det)
    
if det != 0:
        inv = np.linalg.inv(result)
        print("Inverse calculated.")
else:
        print("Inverse not possible (singular matrix).")


end_time = time.time()
print("Time taken: {:.4f} seconds".format(end_time - start_time))

[[23.43345576 25.00109633 24.83206713 ... 22.25843    28.02502865
  26.19211638]
 [22.29575092 23.49661973 24.03486131 ... 21.98994286 27.47609345
  24.83154767]
 [22.28156833 23.74519831 23.37495092 ... 22.71650409 26.43351015
  25.52124973]
 ...
 [21.84477834 24.12945922 23.71099307 ... 20.49615608 25.10868626
  23.52337372]
 [23.25667247 25.41228581 24.66875672 ... 21.57763132 26.29219316
  25.59402536]
 [22.6527596  24.1733071  25.10504754 ... 22.75859795 24.8843812
  26.69543131]]
Determinant: -2.483821005444199e+52
Inverse calculated.
Time taken: 0.0677 seconds
